version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            echo 'export TAG=build-${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=shanemalachow/guiltyspark' >> $BASH_ENV
      - setup_remote_docker:
      - run:
          name: Build Docker Image
          command: |
            docker build -t $IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $IMAGE_NAME:$TAG